WIP: nullable 1:1 connections
tarantool/graphql.0 pull request #67
Opened 2018-03-06 01:58 UTC by Totktonada

TBD:
* stable test
* FULL MATCH constraint check (either all nulls or all non-nulls)
* tests on shard

2018-03-07 01:13 UTC, Totktonada commented
@Khatskevich @SudoBobo The PR is ready for review.

2018-03-07 08:36 UTC, Khatskevich requested changes
First phase, but not the last...

2018-03-07 08:36 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +                'connection.type must be 1:1, 1:1* or 1:N, got ' .. c.type)
I do not like * syntax. It looks like magic for the person who see it the first time

2018-03-07 08:36 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +--- state.nullable_collection_types (its are gql types)
Those are

2018-03-07 08:36 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +                'connection.type must be 1:1, 1:1* or 1:N, got ' .. c.type)
Additional field (nullable=true) would also simplify your code. Because now 1:1 and 1:1* are generally the same, but you check both

2018-03-07 08:36 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +--- state.nullable_collection_types
Why do you rename it?

2018-03-07 08:36 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +                    state.nullable_collection_types[c.destination_collection])
Why you do not reuse destination type?

2018-03-07 08:36 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +                    state.nullable_collection_types[c.destination_collection])
You can make collection nonnull 2 times? I do not understand completely what would happen in this case.

2018-03-07 08:36 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +        return avro_t == 'record' and types.nonNull(res) or res
May be I am wrong, but I suppose that if the type is nullable or not should decide type user, but not type itself.
I suggest always return nullable types.

2018-03-07 08:36 UTC, Khatskevich commented on test/testdata/nullable_1_1_conn_testdata.lua
> +        +---------------------+
What is that?) Why do you print it? Moreover it is not printed in shard tests. Better to just leave it as a comment?

2018-03-07 08:36 UTC, Khatskevich commented on test/testdata/nullable_1_1_conn_testdata.lua
> +-- The example was inspired by [1]. Consider [2] for the problem description
It is up to you, but I do not like those teste. In my opinion we need to:
1. Write common tests
2. Check results in tests

Pros:
1. To validate test results we do not need to read 3 result files
2. The code you copy can contain small bugs, so, it should also be read 3 times
It is just a waste of time!

2018-03-07 11:30 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +                'connection.type must be 1:1, 1:1* or 1:N, got ' .. c.type)
I want to be consistent with our extended avro-schema approach.

2018-03-07 11:31 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +--- state.nullable_collection_types (its are gql types)
Fixed.

2018-03-07 12:36 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +--- state.nullable_collection_types
I generally against common words to refer specific things. This field contains only collection types (and does not contain, say, nested records) and that types converted to nullable ones (because of lazy types evaluation, consider comments). So more specific name `nullable_collection_types` is fair term for that. Maybe `collection_types_nullable` is better, though.

2018-03-07 12:38 UTC, Totktonada commented on test/testdata/nullable_1_1_conn_testdata.lua
> +        +---------------------+
Forgot to print in shard tests. Will do. It was for convenient investigation of run of the test.

2018-03-07 12:47 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +        return avro_t == 'record' and types.nonNull(res) or res
Interesting idea, but it would be architectural change. It is smth that we can have in our minds to consider. Thanks!

2018-03-07 12:54 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +                    state.nullable_collection_types[c.destination_collection])
1. Fixed.
2. I’m sure that collection types are nullable because it is how I save it.

2018-03-07 13:29 UTC, Totktonada commented on test/testdata/nullable_1_1_conn_testdata.lua
> +        +---------------------+
Consider yaml module in tarantool:

third_party/lua-yaml/lyaml.cc
```
         } else if (strstr(str, "\n\n") != NULL) {
            /*  
             * Tarantool-specific: use literal style for string with empty lines.
             * Useful for tutorial().
             */
            style = YAML_LITERAL_SCALAR_STYLE;
         }   
```

I added two newlines in the begin of the string and got right output for the shard tests.

2018-03-07 13:35 UTC, Totktonada commented on test/testdata/nullable_1_1_conn_testdata.lua
> +-- The example was inspired by [1]. Consider [2] for the problem description
I think I should work on reducing code size of the tests. Maybe I should consider 'common' test suite + tap13, but I want to: run local test as just file, don’t repeat the sime initialization / running steps, working shard module reloading. I’ll consider your pain at reading in the next PRs.

2018-03-12 08:48 UTC, Khatskevich requested changes
I request some important changes.
See comments.

2018-03-12 08:48 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +                            are_all_parts_null = false
I suppose this code should be moved outside of the closure (as a call to a function)

2018-03-12 08:48 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +                        assert(is_full_match_ok,
Delete if, it is useless because your assert contains the same condition

2018-03-12 08:48 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +                    local is_full_match_ok = are_all_parts_null or
I do not like the extra variable with the strange name `is_full_match_ok`. It does not increase readability and should be used only once in the following assert, please, use just `are_all_parts_null or are_all_parts_non_null` instead (in assert).

2018-03-12 08:48 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +                            'only 1:1* or 1:N connections can have ' ..
Do not split the user-visible output into lines (grep). We should follow this rule in the future too.
To maintain good code style, I propose to create a file with error messages.

Moreover, in this particular case, I believe you should provide extra information about the failed object. Because even after user sees this error, it is impossible to debug the case.

2018-03-12 08:48 UTC, Khatskevich commented on graphql/tarantool_graphql.lua
> +                    -- destination object(s)
Half of your comments are sentences with a dot at the end and start with a capital teller, and half of them are just text. I like the first option more. Let's follow the style?

2018-03-12 08:48 UTC, Khatskevich commented on test/testdata/nullable_1_1_conn_testdata.lua
> +            localpart = random_string(16):hex(),
Please, do not use random functions for pest data. This field can not be used in test output because it is not consistent.

2018-03-12 08:48 UTC, Khatskevich commented on test/testdata/nullable_1_1_conn_testdata.lua
> +    -- nulls
Please, create 1 failing test.

2018-03-12 11:01 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +                        assert(is_full_match_ok,
Please, read the comment for this if.

2018-03-12 11:50 UTC, Totktonada commented on test/testdata/nullable_1_1_conn_testdata.lua
> +    -- nulls
I have two failing tests here. Commented explicitly that they are fails.

2018-03-12 11:54 UTC, Totktonada commented on test/testdata/nullable_1_1_conn_testdata.lua
> +            localpart = random_string(16):hex(),
I initialized PRNG with a constant seed. You can use it in the output and it will be the same.

2018-03-12 13:19 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +                    local is_full_match_ok = are_all_parts_null or
Ok, I’ll use name `ok`. Don’t want to carry lines, it looks ugly here.

2018-03-12 13:20 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +                            are_all_parts_null = false
I’ll think about that before merge, but I’ll skip it now. Thanks for the point.

2018-03-12 13:27 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +                            'only 1:1* or 1:N connections can have ' ..
We discussed the line carrying in the case in context of tarantool code style and decided to force formal line lenght limit. So I’ll prefer to fit the limit, but I’ll try to split a message by meaningful parts.

extra info: TBD

2018-03-12 23:47 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +                            'only 1:1* or 1:N connections can have ' ..
extra info: added

2018-03-12 23:48 UTC, Totktonada commented on test/testdata/nullable_1_1_conn_testdata.lua
> +            localpart = random_string(16):hex(),
Found that math.random() gives different numbers on different machines. Implemented simple PRNG in the test.

2018-03-12 23:54 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +                    -- destination object(s)
My approach is the following. I use small letter in the begin and omit period at the end when the comment is one clause or like so (maybe even an expanded sentence, but only one). Several sentences started from capital letter and have period at the end.

Here we have several sentences, so I reformatted this into one multi-sentence comment (capital letter + period).

2018-03-12 23:57 UTC, Totktonada commented on graphql/tarantool_graphql.lua
> +                            are_all_parts_null = false
It seems that similar effort was made by @SudoBobo in the scope of #8. I’m going to leave it as is for now. Feel free to file an issue re code refactoring if you want to track this.

2018-03-13 11:05 UTC, Khatskevich approved these changes
Everything is negotiated or fixed. ACK

2018-03-13 21:07 UTC, merged